-- MySQL Script generated by MySQL Workbench
-- Fri May 13 12:10:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Facundo_Azcurra
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Facundo_Azcurra
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Facundo_Azcurra` DEFAULT CHARACTER SET latin1 ;
USE `Facundo_Azcurra` ;

-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`Rooms` (
  `idRooms` INT NOT NULL,
  `isAvailable` TINYINT NOT NULL,
  `floor` INT NOT NULL,
  `MedicId` INT(11) NOT NULL,
  `DoctorOfficeId` INT(11) NOT NULL,
  PRIMARY KEY (`idRooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`Hospital` (
  `idHospital` INT NOT NULL,
  `roomId` INT NOT NULL,
  `MedicId` INT(11) NOT NULL,
  `AdministrativesId` INT(11) NOT NULL,
  PRIMARY KEY (`idHospital`),
  INDEX `fk_Hospital_Rooms1_idx` (`roomId` ASC, `MedicId` ASC, `AdministrativesId` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_Rooms1`
    FOREIGN KEY (`roomId` , `MedicId` , `AdministrativesId`)
    REFERENCES `Facundo_Azcurra`.`Rooms` (`idRooms` , `MedicId` , `DoctorOfficeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`Administratives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`Administratives` (
  `idAdministratives` INT(11) NOT NULL,
  `HospitalID` INT NOT NULL,
  PRIMARY KEY (`idAdministratives`),
  INDEX `fk_Administratives_Hospital1_idx` (`HospitalID` ASC) VISIBLE,
  CONSTRAINT `fk_Administratives_Hospital1`
    FOREIGN KEY (`HospitalID`)
    REFERENCES `Facundo_Azcurra`.`Hospital` (`idHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`AmbulanceDriver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`AmbulanceDriver` (
  `idAmbulanceDriver` INT(11) NOT NULL,
  `hasPCRKnowledge` TINYINT(4) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAmbulanceDriver`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`Ambulances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`Ambulances` (
  `idAmbulances` INT(11) NOT NULL,
  `ambulanceDriverId` INT(11) NOT NULL,
  `ambulance` INT(11) NOT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idAmbulances`),
  INDEX `fk_Ambulances_AmbulanceDriver1_idx` (`ambulance` ASC) VISIBLE,
  INDEX `fk_Ambulances_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE,
  CONSTRAINT `fk_Ambulances_AmbulanceDriver1`
    FOREIGN KEY (`ambulance`)
    REFERENCES `Facundo_Azcurra`.`AmbulanceDriver` (`idAmbulanceDriver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ambulances_Hospital1`
    FOREIGN KEY (`Hospital_idHospital`)
    REFERENCES `Facundo_Azcurra`.`Hospital` (`idHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`DoctorOffice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`DoctorOffice` (
  `idDoctorOffice` INT(11) NOT NULL,
  PRIMARY KEY (`idDoctorOffice`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`Medics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`Medics` (
  `idMedics` INT(11) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `DoctorOfficeId` INT(11) NOT NULL,
  `RoomId` INT NOT NULL,
  PRIMARY KEY (`idMedics`),
  UNIQUE INDEX `idx_Medics_idMedics` (`idMedics` ASC) VISIBLE,
  INDEX `fk_Medics_DoctorOffice1_idx` (`DoctorOfficeId` ASC) VISIBLE,
  INDEX `fk_Medics_Rooms1_idx` (`RoomId` ASC) VISIBLE,
  CONSTRAINT `fk_Medics_DoctorOffice1`
    FOREIGN KEY (`DoctorOfficeId`)
    REFERENCES `Facundo_Azcurra`.`DoctorOffice` (`idDoctorOffice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medics_Rooms1`
    FOREIGN KEY (`RoomId`)
    REFERENCES `Facundo_Azcurra`.`Rooms` (`idRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`HealthCareInsurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`HealthCareInsurance` (
  `HealthCareID` INT(11) NOT NULL,
  `price` DOUBLE NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`HealthCareID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`Patients` (
  `idPatients` INT(11) NOT NULL,
  `isAttended` TINYINT(1) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `HealthCareID` INT(11) NOT NULL,
  PRIMARY KEY (`idPatients`),
  INDEX `fk_Patients_HealthCareInsurance1_idx` (`HealthCareID` ASC) VISIBLE,
  CONSTRAINT `fk_Patients_HealthCareInsurance1`
    FOREIGN KEY (`HealthCareID`)
    REFERENCES `Facundo_Azcurra`.`HealthCareInsurance` (`HealthCareID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`Appointments` (
  `idAppointments` INT(11) NOT NULL,
  `MedicID` INT(11) NOT NULL,
  `AppointmentRoom` INT(11) NOT NULL,
  `PatientId` INT(11) NOT NULL,
  PRIMARY KEY (`idAppointments`),
  INDEX `fk_Appointments_Medics1_idx` (`MedicID` ASC, `AppointmentRoom` ASC) VISIBLE,
  INDEX `fk_Appointments_Patients1_idx` (`PatientId` ASC) VISIBLE,
  CONSTRAINT `fk_Appointments_Medics1`
    FOREIGN KEY (`MedicID` , `AppointmentRoom`)
    REFERENCES `Facundo_Azcurra`.`Medics` (`idMedics` , `DoctorOfficeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointments_Patients1`
    FOREIGN KEY (`PatientId`)
    REFERENCES `Facundo_Azcurra`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`Chirophane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`Chirophane` (
  `idChirophane` INT(11) NOT NULL,
  `isAvailable` TINYINT(4) NOT NULL,
  `floor` INT(11) NOT NULL,
  `ChirophaneRoom` INT NOT NULL,
  PRIMARY KEY (`idChirophane`),
  INDEX `fk_Chirophane_Rooms1_idx` (`ChirophaneRoom` ASC) VISIBLE,
  CONSTRAINT `fk_Chirophane_Rooms1`
    FOREIGN KEY (`ChirophaneRoom`)
    REFERENCES `Facundo_Azcurra`.`Rooms` (`idRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`ChirophaneTrainees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`ChirophaneTrainees` (
  `idChirophanTrainees` INT(11) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `ChirophaneID` INT(11) NOT NULL,
  PRIMARY KEY (`idChirophanTrainees`),
  INDEX `fk_ChirophaneTrainees_Chirophane1_idx` (`ChirophaneID` ASC) VISIBLE,
  CONSTRAINT `fk_ChirophaneTrainees_Chirophane1`
    FOREIGN KEY (`ChirophaneID`)
    REFERENCES `Facundo_Azcurra`.`Chirophane` (`idChirophane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`DeliveryRooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`DeliveryRooms` (
  `idDeliveryRooms` INT(11) NOT NULL,
  `childbirthDoctorId` INT(11) NOT NULL,
  `isAvailable` TINYINT(4) NOT NULL,
  `Rooms_idRooms` INT NOT NULL,
  `Rooms_Medics_idMedics` INT(11) NOT NULL,
  `DeliveryRoomsMedicId` INT NOT NULL,
  PRIMARY KEY (`idDeliveryRooms`),
  INDEX `fk_DeliveryRooms_Rooms1_idx` (`Rooms_idRooms` ASC, `Rooms_Medics_idMedics` ASC, `DeliveryRoomsMedicId` ASC) VISIBLE,
  CONSTRAINT `fk_DeliveryRooms_Rooms1`
    FOREIGN KEY (`Rooms_idRooms` , `Rooms_Medics_idMedics`)
    REFERENCES `Facundo_Azcurra`.`Rooms` (`idRooms` , `MedicId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`IntensiveCare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`IntensiveCare` (
  `idIntensiveCare` INT(11) NOT NULL,
  `IntensiveCareRoomId` INT NOT NULL,
  `IntensiveCareAppointedMedic` INT(11) NOT NULL,
  PRIMARY KEY (`idIntensiveCare`),
  INDEX `fk_IntensiveCare_Rooms1_idx` (`IntensiveCareRoomId` ASC, `IntensiveCareAppointedMedic` ASC) VISIBLE,
  CONSTRAINT `fk_IntensiveCare_Rooms1`
    FOREIGN KEY (`IntensiveCareRoomId` , `IntensiveCareAppointedMedic`)
    REFERENCES `Facundo_Azcurra`.`Rooms` (`idRooms` , `MedicId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`Managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`Managers` (
  `idManagers` INT(11) NOT NULL,
  `economicsManager` TINYINT(4) NOT NULL,
  `directorManager` TINYINT(4) NOT NULL,
  `HospitalId` INT NOT NULL,
  PRIMARY KEY (`idManagers`),
  INDEX `fk_Managers_Hospital1_idx` (`HospitalId` ASC) VISIBLE,
  CONSTRAINT `fk_Managers_Hospital1`
    FOREIGN KEY (`HospitalId`)
    REFERENCES `Facundo_Azcurra`.`Hospital` (`idHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`MedicTrainees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`MedicTrainees` (
  `idMedicTrainees` INT(11) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `MedicRoomId` INT(11) NOT NULL,
  PRIMARY KEY (`idMedicTrainees`),
  INDEX `fk_MedicTrainees_Medics1_idx` (`MedicRoomId` ASC) VISIBLE,
  CONSTRAINT `fk_MedicTrainees_Medics1`
    FOREIGN KEY (`MedicRoomId`)
    REFERENCES `Facundo_Azcurra`.`Medics` (`DoctorOfficeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`Nurses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`Nurses` (
  `idNurses` INT(11) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `IntensiveCareRoomId` INT(11) NOT NULL,
  `ChirophaneRoomId` INT(11) NOT NULL,
  PRIMARY KEY (`idNurses`),
  INDEX `fk_Nurses_IntensiveCare1_idx` (`IntensiveCareRoomId` ASC) VISIBLE,
  INDEX `fk_Nurses_Chirophane1_idx` (`ChirophaneRoomId` ASC) VISIBLE,
  CONSTRAINT `fk_Nurses_IntensiveCare1`
    FOREIGN KEY (`IntensiveCareRoomId`)
    REFERENCES `Facundo_Azcurra`.`IntensiveCare` (`idIntensiveCare`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nurses_Chirophane1`
    FOREIGN KEY (`ChirophaneRoomId`)
    REFERENCES `Facundo_Azcurra`.`Chirophane` (`idChirophane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Facundo_Azcurra`.`Prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Facundo_Azcurra`.`Prescription` (
  `idPrescription` INT(11) NOT NULL,
  `prescriptionPrice` INT(11) NOT NULL,
  `MedicId` INT(11) NOT NULL,
  `PatientId` INT(11) NOT NULL,
  PRIMARY KEY (`idPrescription`),
  INDEX `fk_Prescription_Medics1_idx` (`MedicId` ASC) VISIBLE,
  INDEX `fk_Prescription_Patients1_idx` (`PatientId` ASC) VISIBLE,
  CONSTRAINT `fk_Prescription_Medics1`
    FOREIGN KEY (`MedicId`)
    REFERENCES `Facundo_Azcurra`.`Medics` (`idMedics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescription_Patients1`
    FOREIGN KEY (`PatientId`)
    REFERENCES `Facundo_Azcurra`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
